### ISSUE TITLE
Twilio starter app is misleading

### ISSUE THREAD

**Issue by Maxim-Filimonov** [postverta/postverta#4]
Hi,
I like the idea of your service so I wanted to try to use twilio starter kit. However, as I was following the README I've noticed that there is a misleading instruction there:
> Request for an incoming phone number, and configure its voice and messaging webhook URLs as http://app-name.app.postverta.com/call and http://app-name.postverta.com/message

I have tried to perform post request to my app and it doesn't work with http endpoint. Only with https.
However, I cannot use https endpoint with twilio as it gives invalid certificate error :\

**Comment by angl** [comment]
Thanks for the feedback and sorry for the issues. It was an oversight when we moved the whole thing from http to https when taking the service out of private beta. I have fixed the instruction and added the missing certificate. You should be good to go now. I'm closing the issue, but feel free to re-open it if you still have trouble getting twilio to work.
